<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activation Page</title>
</head>
<body>
<div style="background: aqua;">
    <h1>HELLO ${username}</h1>
    <!--<img src="data:image/jpg;base64, " alt="">-->
    <img src="cid:image_id" alt="" width="500px">
    <h2>In Order To Activate Your Account Click Link Below</h2>
    <a href="https://online.pdp.uz" target="_blank">activate</a>
</div>
</body>
</html>