openapi: 3.0.2
info:
  title: Spring 6 Swagger 2 YAML Example
  description: Spring 6 Swagger Simple Application
  termsOfService: http://swagger.io/terms/
  contact:
    url: https://github.com/jlkesh
    email: apiteam@swagger.io
    name: Elmurodov Javohir
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.4
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
    description: Production Service
  - url: http://localhost:9090
    description: Test Service
tags:
  - name: Category
    description: Category Entity
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /api/category/create:
    post:
      tags:
        - Category
      summary: Create Category Entity
      description: Create Category Entity
      requestBody:
        description: Category Fill to All Fields
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        201:
          description: Category Successfully Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        400:
          description: Invalid Validation
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InvalidValidationException'
  /api/category/update:
    put:
      tags:
        - Category
      summary: Update Category Entity
      description: Update Category Entity
      requestBody:
        description: Category Fill to All Fields
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        200:
          description: Successfully Updated Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        400:
          description: Invalid Validation
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InvalidValidationException'
        404:
          description: Category Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotFound'
  /api/category/delete/{id}:
    delete:
      tags:
        - Category
      summary: Deleted Category Entity
      description: Deleted Category Entity
      parameters:
        - name: id
          in: query
          description: Must Be Enter Id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Successfully Deleted - Category
        400:
          description: Invalid Validation
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InvalidValidationException'
        404:
          description: Category Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotFound'

  /api/category/get/{id}:
    get:
      tags:
        - Category
      summary: Get Category Entity
      description: Get Category Entity
      parameters:
        - name: id
          in: query
          description: Must Be Enter Id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successfully Get - Category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        400:
          description: Invalid Validation
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InvalidValidationException'
        404:
          description: Category Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotFound'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: category name
        code:
          type: string
          example: category code
  responses:
    NotFound:
      description: Entity not found
    InvalidValidationException:
      description: Invalid Validation
    RuntimeException:
      description: Entity Created Exception